---
version: 2
updates:
  - directory: "/"
    groups:
      commitlint:
        patterns:
          - "@commitlint/*"
      typescript-eslint:
        patterns:
          - "@typescript-eslint/*"
    open-pull-requests-limit: 10
    package-ecosystem: npm
    schedule:
      interval: daily
      time: "04:00"
    assignees:
      - "kampfmoehre"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
      time: "04:00"
    open-pull-requests-limit: 10
    assignees:
      - "kampfmoehre"
