version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.22
    - 14.14.24
    - 14.14.25
    - 14.14.26
    - 14.14.28
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.23.0
    - 7.24.0
  - dependency-name: "@typescript-eslint/parser"
    versions:
    - 4.20.0
    - 4.21.0
  - dependency-name: "@typescript-eslint/eslint-plugin"
    versions:
    - 4.20.0
    - 4.21.0
  - dependency-name: "@types/chai"
    versions:
    - 4.2.16
  - dependency-name: husky
    versions:
    - 5.1.0
    - 5.1.1
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: eslint-plugin-mocha
    versions:
    - 8.0.0
    - 8.1.0
  - dependency-name: semantic-release
    versions:
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: "@commitlint/cli"
    versions:
    - 11.0.0
    - 12.0.0
  - dependency-name: eslint-config-prettier
    versions:
    - 8.0.0
  - dependency-name: "@types/sinon"
    versions:
    - 9.0.10
  - dependency-name: npm-registry-fetch
    versions:
    - 4.0.7
  - dependency-name: typescript
    versions:
    - 4.1.3
    - 4.1.4
    - 4.1.5
  - dependency-name: lint-staged
    versions:
    - 10.5.3
  - dependency-name: npm-user-validate
    versions:
    - 1.0.1
